services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    image: scraper:latest
    volumes:
      - ./reports:/app/reports
      - ./sources:/app/sources
    env_file:
      - .env